### ISSUE TITLE
Circular Reference Error with Array of Recursive Objects

### ISSUE THREAD

**Issue by akifunal** [ardatan/feTS#1827]
**Describe the bug**

I previously opened an issue #1823 related to a "Type of property 'x' circularly references itself" error, which was resolved (thanks for that!). The fix worked well for our initial cases.  I’ve now encountered another scenario where the error reappears. This time, it occurs with an array of objects that reference a recursive schema.

**To Reproduce** Steps to reproduce the behavior:

[typescriptlang playground](https://www.typescriptlang.org/play/?ssl=71&ssc=1&pln=1&pc=1#code/JYWwDg9gTgLgBDAnmApnA3nActEBDAG2AC8UB5AQQGUAaOSqgWQgBMUC6GyBXGMXuAF84AMygQQcAOQiUMAM5SAsAChVKAB6RYcAMYQAdvPgwUxhnAC8GVQEgIqA3jDAAXHABEAZgB0ABh8vDxo7YAMRCHd0O1sANxQoeWBDdw8ARmCYmGAYAhRUgBUoFDQAWnpHCgAFAEk4Xz9MlVtbNnldKGAwbJSY2w8CgAtgeTgRuDw4eTxwPLgIEQRilCaW0ygQeTIRKgTY4F18z0GYPlcAenP5AHc8AHM7hJ9k8-XN89XBEOawPBhB+RRGIeV7LDxA5otR4wCEtNb3QFwADaHhgYIAut84bZ5NwQPgoIhUgBxORLEqrOFtDpdHoGVKUloOBJ-ZIGGosVLQooUrFw4rySBGMyw7EeABMfkaoux1M63TZqVxukO8nkIm4BHmqCgrMMjLh+gMpmNMrFzjARF0eoM5wAVvJ9Wbse1Bih8M7sQASYoiVIAYnO+nAhhQxvkV10bvwEZ5KAASmYhfIVnzsS0vn1sZnIdm0xn8-0ACx+Ivgmy5qlmGkKlKeONwAwQeARbgGFgG2w5vN9btdrHd4NCsMKUWu914RHRXNxxOCwwps1IVDuKQQABGdpQuhgUnzYHEOuyIor6ajwAInNP6Z9KD90kDQ9D4cj0cn5xwbD3Wf7P51jvZK9MGXI4pDCUxHigPdRFwP5V3ArxxSkIR8z7X9c0-I5p2xEDUg3LcdwNA9mVgYAT2w7EDDxdcEk9XDPHAlBIM7WwIg2OCGONAA2MtC1sTQZktI40j8Qs0Jac9L09W97w8R8JGHF9xxjD9WFTH9xLQvtuxzYRJz0BcYAAblUVQQLgAozBgAARP5JmsBhmDYAgAB47BwdiiFIBgXJAhYECshgAD4sSkTDlBUILTJUczLOMLwrHoageD4XgXI8-AvPIahfOQFB-NMcxqBC6RQRKaCpGhCrJT8KQgpMlQgA)

**Expected behavior**

I expected this recursive array structure to work without triggering a circular reference error, especially given that a similar issue was previously resolved.

**Environment:**

- OS: MacOS Sonoma 14.6.1
- `package-name...`: fets@0.8.3
- NodeJS: 20.14.0
- TypeScript: 5.5.4

**Additional context**

This is a similar issue to the one you resolved before, but it involves arrays of recursive objects, which seems to introduce a new layer of complexity.

**Comment by scamden** [comment]
Thanks for the fix, i believe I'm running into this error as well. Is there a recent release that includes this? The latest i see on npm is from a year ago.

**Comment by ardatan** [comment]
I just released it so it will be available soon!

**Comment by scamden** [comment]
@ardatan Is this the release? seems like it failed maybe? https://github.com/ardatan/feTS/actions/runs/23503701669/job/68405589047#step:11:5

**Comment by ardatan** [comment]
Sorry for that! Should be good now!

**Comment by scamden** [comment]
Thanks so much! I got it but looks like i still have the issue. I'll open a new issue I guess? Will do my best to nail down a repro.

**Comment by ardatan** [comment]
Could you create a new reproduction PR?

**Comment by scamden** [comment]
> Could you create a new reproduction PR?

Absolutely: https://github.com/ardatan/feTS/issues/3689
